# Site info
title               : Gumgood
description         : AI 공부하는 블로그입니다!!

# Handling Reading
include             : ["_pages", "_sass"]
exclude             : ["Gemfile", "Gemfile.lock", "README.md"]

# Build trick
theme: null