# Site info
title               : Gumgood
description         : AI 공부하는 블로그입니다!!
author:
  avatar            : https://avatars.githubusercontent.com/u/17876281
  organization      : Samsung Research
  email             : gumgood@naver.com
  github            : gumgood

# Where things are
collections_dir     : contents
collections:
  assets:
    output          : true
    permalink       : :name

# Handling Reading
include             : ["_pages", "_sass"]
exclude             : ["Gemfile", "Gemfile.lock", "README.md"]

defaults:
  -
    scope:
      type          : pages
    values:
      layout        : default
      permalink     : :basename
  -
    scope:
      type          : posts
    values:
      permalink     : :title

# Build trick
theme: null
