# Site settings
title:          Gumgood
description:    이상원(@Gumgood)의 블로그입니다. 
url:            https://gumgood.github.io

# Author
author:
  name:         Sangwon Lee 
  email:        gumgood@naver.com
  github:       gumgood

# Permalinks
permalink:      /:title

# Collections
collections:
  category:
    output: true
    permalink: /categories/:path
  subcategory:
    output: true
    permalink: /categories/:path
  tags:
    output: true
    permalink: /tags/:path

# Default
defaults:
  - scope:
      type: category
    values:
      layout: category
  - scope:
      type: subcategory
    values:
      layout: subcategory
  - scope:
      type: tags
    values:
      layout: tag


# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
include: ["_page"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE"]
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true
