# --------------------------- Site variables ---------------------------

# Site info
title               : Gumgood
description         : 이상원(@Gumgood)의 블로그입니다. 
url                 : https://gumgood.github.io

# Author
author:
  name              : Sangwon Lee 
  email             : gumgood@naver.com
  github            : gumgood

# --------------------------- Configurations ---------------------------

# Where things are
sass:
  style             : compressed
collections:
  categories:
    output          : true
  tags:
    output          : true

# Handling Reading
include             : ["_page"]
exclude             : ["Gemfile", "Gemfile.lock", "README.md", "LICENSE"]

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Outputting
permalink           : /:title
#paginate_path       : /page:num

# Markdown Processors
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers  : true

# Defaults
defaults:
  - scope:
      type          : pages
    values:
      layout        : default
  - scope:
      type          : posts
    values:
      layout        : post
  - scope:
      type          : categories
    values:
      permalink     : /categories/:path
      layout        : post-list
  - scope:
      type          : tags
    values:
      permalink     : /tags/:path
      layout        : post-list
      