# --------------------------- Site variables ---------------------------

# Site info
title               : Gumgood
description         : 이상원(@Gumgood)의 블로그
url                 : https://gumgood.github.io

# Author
author:
  name              : Sangwon Lee 
  email             : gumgood@naver.com
  github            : gumgood

# --------------------------- Configurations ---------------------------

# Where things are
sass:
  style             : compressed

# Handling Reading
include             : ["_data", "_page"]
exclude             : ["Gemfile", "Gemfile.lock", "README.md", "LICENSE"]

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Markdown Processors
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers  : true

collections:
  category:
    output          : true
  tag:
    output          : true

# Paginate
paginate            : 10
paginate_path       : /:num

# Outputting
permalink           : /:title

# Defaults
defaults:
  - 
    scope:
      type          : posts
    values:
      layout        : post
      sitemap       : true
  - 
    scope:
      path          : _pages
    values:
      layout        : default
      sitemap       : false
      permalink     : /:basename
  - 
    scope:
      type          : category
    values:
      layout        : post-list
      sitemap       : false
      permalink     : /category/:path
  - 
    scope:
      type          : tag
    values:
      layout        : post-list
      sitemap       : false
      permalink     : /tag/:path
